FROM ubuntu:18.04
LABEL maintainer="Atlanta Tecnologia da Informação"

ENV container docker
ENV DEBIAN_FRONTEND noninteractive
ENV TIMEZONE 'America/Fortaleza'
ENV LC_ALL C.UTF-8
#ENV LANG C.UTF-8
ENV LANG pt_BR.UTF-8

RUN sed -i 's/# deb/deb/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y  locales apt-utils
   
RUN echo $TIMEZONE > /etc/timezone && \
    apt-get install -y tzdata && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN apt-get install -y sudo  curl ca-certificates gnupg sudo apt-utils
    
RUN apt-get install -y dialog && \
	locale-gen $LANG && \
	dpkg-reconfigure locales --force
RUN apt-get update && apt-get install -y  software-properties-common apt-utils
RUN apt-get  install -y \ 
    apache2-bin libapache2-mod-php php-dev \ 
    libmcrypt-dev php-pear php7.2-curl php7.2 \ 
    php7.2-ldap php7.2-mysql  \
    php7.2-gd php7.2-xml patch curl vim git mysql-client wget unzip

RUN phpenmod mcrypt && phpenmod gd
RUN a2enmod xml2enc && a2enmod rewrite

RUN sed -i 's/variables_order = .*/variables_order = "EGPCS"/' /etc/php/7.2/apache2/php.ini
RUN sed -i 's/variables_order = .*/variables_order = "EGPCS"/' /etc/php/7.2/cli/php.ini

RUN useradd --uid 1000 --gid 50 docker

RUN echo export APACHE_RUN_USER=docker >> /etc/apache2/envvars
RUN echo export APACHE_RUN_GROUP=staff >> /etc/apache2/envvars

COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf

RUN chown -R docker /var/www/html

WORKDIR /var/www/html

RUN wget -q "http://www.sentrifugo.com/home/downloadfile?file_name=Sentrifugo.zip" -O Sentrifugo.zip 
#COPY Sentrifugo.zip /var/www/html/
RUN unzip Sentrifugo.zip && mv Sentrifugo_3.2 sentrifugo

WORKDIR /var/www/html/sentrifugo
RUN chown -R docker .

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN chmod 777 -R public/downloads public/uploads public/email_constants.php \
public/emptabconfigure.php \
public/site_constants.php \
public/db_constants.php \
public/application_constants.php \
public/mail_settings_constants.php \
logs/application.log \
application/modules/default/plugins/AccessControl.php \
install

VOLUME /var/www/html/sentrifugo/public/uploads

VOLUME /var/www/html/sentrifugo/public/downloads

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 80
