version: '3'
services:
  sentrifugo:
    build:
      context: .
      dockerfile: Dockerfile-sentrifugo
    image: atlantatecnologia/sentrifugo:app
    ports:
      - "8080:80"
      - "8443:443"
    devices:
      - "/dev/tty:/dev/tty"
    links:
      - "mariadb:mariadb"
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    image: atlantatecnologia/sentrifugo:mariadb
    #ports:
    #  - "3306:3306"
